### ISSUE TITLE
PCDATA

### ISSUE THREAD

**Issue by ruthtillman** [nodanaonlyzuul/loc-ead-beautifier#1]
1) From the creator of EADiva: I just love the extension, it fixes half the issues that made me recreate the site. (The others were content, which isn't something you can fix through an extension.) The code previewer is lovely and the interlinking--I swear that's half the feedback I get on my site, asking why the other couldn't be interlinked. It's fantastic!

2) Actual issue: Your algorithm is catching #PCDATA and assuming it will also have a page, but the link just takes you to the directory itself. You could either set it to ignore PCDATA (and I'm trying to think if any of these contain CDATA, but I think that's only in attributes, which you don't tinker with) or set it so that if you hover over PCDATA it comes up with a definition of what it is. I may try forking and coding that myself but time's a little wonky right now so I thought I'd submit it as an issue too.

Thanks for making this.

**Comment by nodanaonlyzuul** [comment]
Hey @ruthtillman!

Thanks for the generous feedback and taking time to play with the extension.

Yes - the JavaScript is **very** naive and is gobbling up a few things that it shouldn't.
I'll certainly look into rejecting certain phrases in the HTML - and may ask you to take the branch
for a test spin.

**Comment by nodanaonlyzuul** [comment]
There's a naive fix for this in b5c56edcd021bb58a93885847808b39e9fe03ed4 which has been released in 0.0.3. We no longer wrap "EMPTY" or "#PCDATA" in anchor tags.
Pushed up to the chrome web store just a few moments ago.
