### ISSUE TITLE
Empty treated as element

### ISSUE THREAD

**Issue by jvarghese01** [nodanaonlyzuul/loc-ead-beautifier#2]
http://loc.gov/ead/tglib/elements/colspec.html

minor point: empty as used here is not another ead element and shouldn't be linked.

**Comment by jvarghese01** [comment]
I guess this is more generally covered in issue #1

**Comment by nodanaonlyzuul** [comment]
There's a naive fix for this in b5c56edcd021bb58a93885847808b39e9fe03ed4 which has been released in 0.0.3. We no longer wrap "EMPTY" or "#PCDATA" in anchor tags.
Pushed up to the chrome web store just a few moments ago.
